# Generated by Django 2.1.7 on 2019-03-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20190301_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('cup', 'cup'), (' tsp', 'tsp'), ('tbs', 'tbs'), ('qt', 'qt')], max_length=255),
        ),
    ]
