# Generated by Django 2.1.7 on 2019-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20190301_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
    ]
