# Generated by Django 2.1.7 on 2019-03-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(choices=[('lb', 'lb'), ('oz', 'oz'), ('cup', 'cup'), (' tsp', 'tsp'), ('tbs', 'tbs'), ('qt', 'qt')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('servings', models.IntegerField(default=4)),
                ('directions', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='frontend.Recipe'),
        ),
    ]
